"use client";

export default function SettingsPage() {
  return (
    <div className="p-8 max-w-2xl mx-auto">
      <div className="mb-8">
        <h1 className="text-2xl font-semibold text-[#f1f1f1] mb-1">Settings</h1>
        <p className="text-[13px] text-[#555]">Configure YouTube Factory AI</p>
      </div>

      <div className="space-y-4">
        {[
          { section: "AI Engine", items: [
            { label: "Script model", value: "Claude Sonnet 4.6", type: "text", note: "Used for all script generation" },
            { label: "Max script tokens", value: "4096", type: "text", note: "Maximum tokens per script generation" },
            { label: "QA pass threshold", value: "85", type: "text", note: "Minimum score before regeneration is triggered" },
          ]},
          { section: "Pipeline", items: [
            { label: "Auto-retry failed agents", value: "2", type: "text", note: "Number of retry attempts per agent" },
            { label: "Video ideas per run", value: "8", type: "text", note: "Ideas generated by research agent per run" },
            { label: "Thumbnail concepts", value: "5", type: "text", note: "Number of thumbnail concepts generated" },
          ]},
          { section: "Integrations", items: [
            { label: "YouTube API key", value: "", type: "password", note: "For automated publishing (Phase 2)" },
            { label: "Canva API key", value: "", type: "password", note: "For automated thumbnail rendering (Phase 2)" },
          ]},
        ].map((group) => (
          <div key={group.section} className="bg-[#111] border border-[#2a2a2a] rounded-xl overflow-hidden">
            <div className="px-5 py-3 border-b border-[#1e1e1e]">
              <p className="text-[12px] font-medium text-[#888] uppercase tracking-wider">{group.section}</p>
            </div>
            <div className="divide-y divide-[#1a1a1a]">
              {group.items.map((item) => (
                <div key={item.label} className="flex items-center gap-4 px-5 py-4">
                  <div className="flex-1 min-w-0">
                    <p className="text-[13px] text-[#f1f1f1] mb-0.5">{item.label}</p>
                    <p className="text-[11px] text-[#444]">{item.note}</p>
                  </div>
                  <input
                    type={item.type}
                    defaultValue={item.value}
                    placeholder={item.type === "password" ? "Not configured" : item.value}
                    className="w-40 bg-[#0d0d0d] border border-[#2a2a2a] rounded-lg px-3 py-2 text-[12px] text-[#ccc] outline-none focus:border-[#E24B4A] text-right placeholder:text-[#333]"
                  />
                </div>
              ))}
            </div>
          </div>
        ))}

        <div className="bg-[#1a0808] border border-[#E24B4A22] rounded-xl p-5">
          <p className="text-[12px] font-medium text-[#E24B4A] mb-2">Phase 2 roadmap</p>
          <div className="space-y-1.5">
            {[
              "Automatic YouTube upload via YouTube Data API",
              "Thumbnail A/B testing with performance tracking",
              "Analytics feedback loop (CTR, watch time → scoring model)",
              "Trend monitoring agent (daily niche scans)",
              "Multi-channel support",
            ].map((item) => (
              <div key={item} className="flex gap-2.5 text-[12px] text-[#666]">
                <span className="text-[#E24B4A33]">→</span>{item}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
